// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMN2rCPORQdvaYI5djvPCrYVvDzXtbIMM',
    appId: '1:129193825511:web:3e0a341d804ce26571fe42',
    messagingSenderId: '129193825511',
    projectId: 'mytablettracker',
    authDomain: 'mytablettracker.firebaseapp.com',
    storageBucket: 'mytablettracker.appspot.com',
    measurementId: 'G-LBFH3GW93X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlb6nttdqqMQADNMLyX8OmT8Fv11cKwiQ',
    appId: '1:129193825511:android:86bc725050bef2f371fe42',
    messagingSenderId: '129193825511',
    projectId: 'mytablettracker',
    storageBucket: 'mytablettracker.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhaabv3n9cZR9IRBrJq34a5-n2Q-wg18s',
    appId: '1:129193825511:ios:2497acb377aa437d71fe42',
    messagingSenderId: '129193825511',
    projectId: 'mytablettracker',
    storageBucket: 'mytablettracker.appspot.com',
    iosBundleId: 'com.example.tabletTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhaabv3n9cZR9IRBrJq34a5-n2Q-wg18s',
    appId: '1:129193825511:ios:2497acb377aa437d71fe42',
    messagingSenderId: '129193825511',
    projectId: 'mytablettracker',
    storageBucket: 'mytablettracker.appspot.com',
    iosBundleId: 'com.example.tabletTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMN2rCPORQdvaYI5djvPCrYVvDzXtbIMM',
    appId: '1:129193825511:web:ba576a5afb86941a71fe42',
    messagingSenderId: '129193825511',
    projectId: 'mytablettracker',
    authDomain: 'mytablettracker.firebaseapp.com',
    storageBucket: 'mytablettracker.appspot.com',
    measurementId: 'G-1SEE10REK6',
  );

}